CREATE DATABASE AdmCond
USE [AdmCond]
GO

/****** Object:  Table [dbo].[Casa]    Script Date: 25-04-2024 12:52:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--TABLAS_____________________________________________________________________________________________________________
CREATE TABLE [dbo].[Casa](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Numero] [int] NOT NULL,
	[Letra] [varchar](10) NULL,
	[Deuda] [int] NULL,
 CONSTRAINT [PK_Casa] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [AdmCond]
GO

USE [AdmCond]
GO

/****** Object:  Table [dbo].[JefeHogar]    Script Date: 25-04-2024 13:29:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JefeHogar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](70) NOT NULL,
	[FechaNacimiento] [datetimeoffset] NOT NULL,
	[Run] [varchar](10) NOT NULL,
	[Telefono] [int] NOT NULL,
	[Correo] [varchar](50) NULL,
	[IdCasa] [int] NULL,
 CONSTRAINT [PK_JefeHogar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JefeHogar]  WITH CHECK ADD  CONSTRAINT [FK_JefeHogar_IdCasa] FOREIGN KEY([Id])
REFERENCES [dbo].[JefeHogar] ([Id])
GO

ALTER TABLE [dbo].[JefeHogar] CHECK CONSTRAINT [FK_JefeHogar_IdCasa]
GO

INSERT INTO CASA VALUES(69,'',10000)
INSERT INTO CASA VALUES(71,'',50000)
INSERT INTO CASA VALUES(72,'',20000)
INSERT INTO CASA VALUES(73,'',null)
INSERT INTO CASA VALUES(74,'',null)
INSERT INTO CASA VALUES(75,'',null)
INSERT INTO CASA VALUES(76,'',null)
INSERT INTO CASA VALUES(77,'',null)
INSERT INTO CASA VALUES(78,'',null)
INSERT INTO CASA VALUES(79,'',80000)
INSERT INTO CASA VALUES(80,'',256900)
INSERT INTO CASA VALUES(81,'',null)
INSERT INTO CASA VALUES(82,'',null)
INSERT INTO CASA VALUES(83,'',null)
INSERT INTO CASA VALUES(84,'',120000)
INSERT INTO CASA VALUES(85,'',null)
INSERT INTO CASA VALUES(86,'',null)
INSERT INTO CASA VALUES(87,'',null)
INSERT INTO CASA VALUES(88,'',null)
INSERT INTO CASA VALUES(89,'',null)
INSERT INTO CASA VALUES(105,'',null)

INSERT INTO JefeHogar VALUES ('Vecino Casa89', '1974-01-22','11111111-1',999999999,NULL,1)
INSERT INTO JefeHogar VALUES ('Vecina Casa105', '1972-06-13','22222222-2',988888888,NULL,2)


select * from Casa
select * from JefeHogar
